services:
  database:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: librarydb
    volumes:
      - ./database:/var/lib/postgresql/data
